export * from './InputPage'
export * from './LayoutPage'
export * from './TablePage'
export * from './LinkPage'
export * from './HomePage'
export * from './GlobalStylesPage'
export * from './ButtonPage'
export * from './TextPage'
